import type { Card } from "../domain/card";

export const seedCards: Card[] = [
  {
    id: "demo-quadratic",
    subject: "数学",
    question: "解不等式：x² − 5x + 6 > 0。",
    userAnswer: "由 (x−2)(x−3)>0，得 2 < x < 3。",
    correctAnswer: "x < 2 或 x > 3",
    supplementalNote: "",
    solution: "先求方程的两个根 2、3。二次项系数为正，图像开口向上，因此大于 0 的区间位于两根外侧。",
    errorLocation: "将二次函数大于 0 的区间判断成了两个根之间。",
    errorReason: "混淆了开口向上的二次函数在两根内外的符号规律。",
    errorType: "方法错误",
    knowledgePoints: [
      { id: "kp-quadratic", subject: "数学", chapter: "不等式", name: "一元二次不等式" },
      { id: "kp-graph", subject: "数学", chapter: "函数", name: "函数图像" },
    ],
    assets: [],
    status: "organized",
    revision: 1,
    createdAt: "2026-05-18T01:42:00.000Z",
    updatedAt: "2026-05-18T01:42:00.000Z",
  },
  {
    id: "demo-derivative",
    subject: "数学",
    question: "已知 f(x)=x³−3x，求函数的单调区间。",
    userAnswer: "f′(x)=3x²−3，所以函数在 x>1 时单调递增。",
    correctAnswer: "递增区间为 (−∞,−1) 与 (1,+∞)，递减区间为 (−1,1)",
    supplementalNote: "",
    solution: "令 f′(x)=3(x²−1)，根据导数正负判断各区间的单调性。",
    errorLocation: "解 f′(x)>0 时遗漏了 x<−1 的区间。",
    errorReason: "由 x²>1 推导时只保留了正数分支。",
    errorType: "推理或步骤错误",
    knowledgePoints: [
      { id: "kp-derivative", subject: "数学", chapter: "函数与导数", name: "函数单调性" },
    ],
    assets: [],
    status: "organized",
    revision: 1,
    createdAt: "2026-05-17T13:16:00.000Z",
    updatedAt: "2026-05-17T13:16:00.000Z",
  },
  {
    id: "demo-geometry",
    subject: "数学",
    question: "如图，在 △ABC 中，AB=AC，求证 ∠B=∠C。",
    userAnswer: "",
    correctAnswer: "",
    supplementalNote: "",
    solution: "",
    errorLocation: "",
    errorReason: "",
    errorType: "",
    knowledgePoints: [
      { id: "kp-congruence", subject: "数学", chapter: "三角形", name: "全等三角形" },
    ],
    assets: [],
    status: "draft",
    revision: 1,
    createdAt: "2026-05-16T08:00:00.000Z",
    updatedAt: "2026-05-16T08:00:00.000Z",
  },
];
